secret:
  username: "cG9zdGdyZXM="   # base64-кодированное "postgres"
  password: "cGFzc3dvcmQ="   # base64-кодированное "password"

config:
  database_url: "jdbc:postgresql://host.docker.internal:5432/job4j_devops"
  kafka_bootstrap_servers: "host.docker.internal:9092"

containers:
  image: "katyabahai/job4j_devops:v.1.0.2"



